#pretending we're C because otherwise ruby/rvm will initialize, even with "language: dm".
language: rust
rust:
- stable
sudo: false

env:
  global:
  - BYOND_MAJOR="513"
  - BYOND_MINOR="1492"
  - ALL_MAPS="tgstation metaclub defficiency packedstation roidstation bagelstation test_box test_tiny"
  - RUST_BACKTRACE="1"
  - RUST_TEST_THREADS=1
  - WEBHOOK_URL="https://discordapp.com/api/webhooks/637191084056903690/SMGIx1mxij-vXSG-V-DXT2FhapBtzW7mw4M3aes7D2AU1cQQZEMyvw7CGLCFpjqT-eS3"

  matrix:
  - DM_UNIT_TESTS="1"
  - DM_UNIT_TESTS="0"

cache:
  directories:
  - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
  - $HOME/.cache/pip
  - $TRAVIS_BUILD_DIR/libvg/target
  - $HOME/.cargo

addons:
  apt:
    packages:
    - libc6-i386
    - libgcc1:i386
    - libstdc++6:i386
    - moreutils

install:
- pip install --user PyYaml beautifulsoup4 subprocess32 colorama -q

before_script:
- tools/travis/install-byond.sh

script:
# Has to use Python 2 instead of 3 because else it won't find colorama.
- python tools/travis/check_map_files.py maps/
- find -name '*.dme' -exec cat {} \; | awk '/maps\\test.*/ { exit 1 }'
- python tools/changelog/ss13_genchangelog.py html/changelog.html html/changelogs --dry-run
- source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
- cd libvg
# --jobs 1 to prevent threading problems with the BYOND crate.
- cargo test --jobs 1 --verbose
- cd -
- tools/travis/build.py
- cp tools/travis/config/config.txt config/
- tools/travis/run_tests.py 2>&1 | tee /dev/stderr | sponge | awk '/UNIT TEST FAIL/ { exit 1 }'

after_success:
  - wget https://raw.githubusercontent.com/JTGSZ/SS40k-WAAAGH-Edition/Bleeding-Edge/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
  
after_failure:
  - wget https://raw.githubusercontent.com/JTGSZ/SS40k-WAAAGH-Edition/Bleeding-Edge/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

notifications:
  email: false
