/*
Croneworlds Landmarks
*/
/obj/effect/landmark/cronespawner
	name = "cronespawner"

/obj/effect/landmark/costume/crone

/obj/effect/landmark/costume/crone/New()
	var/landmarkrandom = rand(1, 19)
	switch(landmarkrandom)
		if(1)
//			new /mob/living/simple_animal/hostile/void_dweller(src.loc)
			new /obj/item/device/soulstone(src.loc)
//		if(2)
//			new /mob/living/simple_animal/hostile/shadow(src.loc)
			//new /obj/item/weapon/book/manual/norcbook_two(src.loc)
		if(3)
//			new /mob/living/simple_animal/hostile/zombie(src.loc)
			//new /obj/item/weapon/book/manual/norcbook_four(src.loc)
		if(4)
			new /obj/item/clothing/head/ushanka(src.loc)
			//new /obj/item/weapon/book/manual/norcbook_one(src.loc)
		if(5)
			new /obj/item/clothing/under/gladiator(src.loc)
		if(6)
			new /obj/item/clothing/head/helmet/gladiator(src.loc)
//			new /obj/item/aluminumtube(src.loc)
//		if(7)
//			new /mob/living/simple_animal/hostile/retaliate/daemon/lesser/predator(src.loc) //Putting that instead of nightblood. Nightblood currently steals ghosts, and this is more dangerous.
			//new /obj/item/weapon/book/manual/norcbook_three(src.loc)
		if(8)
			new /obj/item/weapon/chainsword/chaos_chainsword(src.loc)
		if(9)
			new /obj/item/weapon/choppa(src.loc)
			if(prob(40)) new /obj/item/device/soulstone(src.loc)
		if(10)
			new /obj/item/weapon/circular_saw(src.loc)
//			new /obj/item/weapon/storage/toolbox/emergency/cursed(src.loc)
//		if(11)
//			new /obj/item/weapon/powersword/burning(src.loc)
		if(12)
//			new /obj/item/weapon/torture(src.loc)
			new /obj/item/device/mass_spectrometer(src.loc)
		if(13)
			new /obj/machinery/doppler_array(src.loc)
		if(14)
			new /obj/machinery/telepad(src.loc)
			new /obj/item/weapon/bikehorn(src.loc)
//		if(15)
//			new /obj/structure/closet/decrepit(src.loc)
		if(16)
//			new /mob/living/simple_animal/hostile/retaliate/daemon/hulk(src.loc)
//		if(17)
//			new /mob/living/simple_animal/hostile/russian/ranged(src.loc)
//		if(18)
//			new /mob/living/simple_animal/hostile/dark_ghost(src.loc)
		if(19)
			new /mob/living/simple_animal/hostile/giant_spider/hunter(src.loc)
			new /obj/item/weapon/powersword/eldar(src.loc)
	qdel(src)